-- LocalScript placed in StarterPlayerScripts or inside a GUI
local UserInputService = game:GetService("UserInputService")local Players = game:GetService("Players")local player = Players.LocalPlayerlocal PlayerGui = player:WaitForChild("PlayerGui")
-- Create fake gift UIlocal ScreenGui = Instance.new("ScreenGui", PlayerGui)ScreenGui.Name = "FakeGiftGui"
local Frame = Instance.new("Frame", ScreenGui)Frame.Size = UDim2.new(0, 300, 0, 150)Frame.Position = UDim2.new(0.5, -150, 0.5, -75)Frame.BackgroundColor3 = Color3.fromRGB(50, 50, 70)Frame.Visible = falseFrame.Active = trueFrame.Draggable = true
local Title = Instance.new("TextLabel", Frame)Title.Size = UDim2.new(1, 0, 0, 30)Title.BackgroundTransparency = 1Title.Text = "~FAKE ROBUX GIFT~"Title.TextColor3 = Color3.new(1, 1, 1)Title.Font = Enum.Font.SourceSansBoldTitle.TextSize = 20
local CloseButton = Instance.new("TextButton", Frame)CloseButton.Size = UDim2.new(0, 30, 0, 30)CloseButton.Position = UDim2.new(1, -35, 0, 0)CloseButton.Text = "X"CloseButton.Font = Enum.Font.SourceSansBoldCloseButton.TextColor3 = Color3.new(1, 0, 0)CloseButton.BackgroundColor3 = Color3.fromRGB(80, 80, 80)
CloseButton.MouseButton1Click:Connect(function()    Frame.Visible = falseend)
local AmountLabel = Instance.new("TextLabel", Frame)AmountLabel.Position = UDim2.new(0, 10, 0, 40)AmountLabel.Size = UDim2.new(0, 120, 0, 25)AmountLabel.Text = "Enter Robux amount:"AmountLabel.TextColor3 = Color3.new(1, 1, 1)AmountLabel.BackgroundTransparency = 1AmountLabel.Font = Enum.Font.SourceSansAmountLabel.TextSize = 18
local AmountBox = Instance.new("TextBox", Frame)AmountBox.Position = UDim2.new(0, 140, 0, 40)AmountBox.Size = UDim2.new(0, 140, 0, 25)AmountBox.PlaceholderText = "e.g. 1000"AmountBox.Text = ""AmountBox.ClearTextOnFocus = falseAmountBox.Font = Enum.Font.SourceSansAmountBox.TextSize = 18
local SendButton = Instance.new("TextButton", Frame)SendButton.Size = UDim2.new(1, -20, 0, 40)SendButton.Position = UDim2.new(0, 10, 1, -50)SendButton.Text = "Send Gift"SendButton.Font = Enum.Font.SourceSansBoldSendButton.TextSize = 22SendButton.BackgroundColor3 = Color3.fromRGB(0, 170, 0)SendButton.TextColor3 = Color3.new(1, 1, 1)
local MessageLabel = Instance.new("TextLabel", Frame)MessageLabel.Position = UDim2.new(0, 10, 0, 75)MessageLabel.Size = UDim2.new(1, -20, 0, 25)MessageLabel.Text = ""MessageLabel.TextColor3 = Color3.new(0, 1, 0)MessageLabel.BackgroundTransparency = 1MessageLabel.Font = Enum.Font.SourceSansItalicMessageLabel.TextSize = 18
-- Function to open the fake gift UIlocal function openFakeGiftUI()    AmountBox.Text = ""    MessageLabel.Text = ""    Frame.Visible = trueend
-- Bind a key to open the fake gift UI (Escape key example)UserInputService.InputBegan:Connect(function(input, gameProcessed)    if not gameProcessed then        if input.KeyCode == Enum.KeyCode.Escape then            openFakeGiftUI()        end    endend)
-- Simulate the buy gift actionSendButton.MouseButton1Click:Connect(function()    local amount = tonumber(AmountBox.Text)    if amount and amount > 0 then        MessageLabel.Text = "Gift Sent! (" .. tostring(amount) .. " Robux)"        -- You can add additional effects or sounds here    else        MessageLabel.Text = "Please enter a valid amount"        MessageLabel.TextColor3 = Color3.new(1, 0, 0)    endend)
